/*
 * objects/slscsl/win32U/i386/msvc90/release/slscsl/resourceDefines.h
 *    auto generated by c:/Users/tblair/Perforce/slscdev/build/nibuild/export/17.0/17.0.0f1/includes/generate_defines_header.py
 *
 * Copyright (c) 2012-2017,
 * National Instruments Corporation.
 * All rights reserved.
 */

#ifndef ___slscsl_resourceDefines_h___
#define ___slscsl_resourceDefines_h___

#ifdef NIAPAL_USING_NEW_NISTL
   #undef NIAPAL_USING_NEW_NISTL
#endif
#define NIAPAL_USING_NEW_NISTL 0
#ifdef NIMXL_DEBUG
   #undef NIMXL_DEBUG
#endif
#define NIMXL_DEBUG "0"
#ifdef NIINI_FEATURE_SORTED
   #undef NIINI_FEATURE_SORTED
#endif
#define NIINI_FEATURE_SORTED
#ifdef _WIN32_WINNT
   #undef _WIN32_WINNT
#endif
#define _WIN32_WINNT 0x0601
#ifdef __STDC_FORMAT_MACROS
   #undef __STDC_FORMAT_MACROS
#endif
#define __STDC_FORMAT_MACROS 1
#ifdef NIAFA_kUsingExceptions
   #undef NIAFA_kUsingExceptions
#endif
#define NIAFA_kUsingExceptions 1
#ifdef kNIBuildToolsOSEnvEnum
   #undef kNIBuildToolsOSEnvEnum
#endif
#define kNIBuildToolsOSEnvEnum 1
#ifdef NIMXL_CLIENT
   #undef NIMXL_CLIENT
#endif
#define NIMXL_CLIENT "slscsl"
#ifdef nNIAPALS100_kEnableQuarkStatusConversionOperator
   #undef nNIAPALS100_kEnableQuarkStatusConversionOperator
#endif
#define nNIAPALS100_kEnableQuarkStatusConversionOperator 0
#ifdef kNIBuildToolsBuildType
   #undef kNIBuildToolsBuildType
#endif
#define kNIBuildToolsBuildType "release"
#ifdef kClientNamespace
   #undef kClientNamespace
#endif
#define kClientNamespace slscsl
#ifdef _WINNT
   #undef _WINNT
#endif
#define _WINNT
#ifdef kComponentName
   #undef kComponentName
#endif
#define kComponentName "slscsl"
#ifdef __STDC_LIMIT_MACROS
   #undef __STDC_LIMIT_MACROS
#endif
#define __STDC_LIMIT_MACROS 1
#ifdef NIAPAL_INCLUDE_STANDARD_NEW_HEADER
   #undef NIAPAL_INCLUDE_STANDARD_NEW_HEADER
#endif
#define NIAPAL_INCLUDE_STANDARD_NEW_HEADER 1
#ifdef kNIBuildToolsProcessorEnum
   #undef kNIBuildToolsProcessorEnum
#endif
#define kNIBuildToolsProcessorEnum 1
#ifdef kNIBuildToolsCompilerEnum
   #undef kNIBuildToolsCompilerEnum
#endif
#define kNIBuildToolsCompilerEnum 7
#ifdef kNIBuildToolsCompiler
   #undef kNIBuildToolsCompiler
#endif
#define kNIBuildToolsCompiler "msvc90"
#ifdef SYSAPICPP_SYSAPI_SDK_VERSION
   #undef SYSAPICPP_SYSAPI_SDK_VERSION
#endif
#define SYSAPICPP_SYSAPI_SDK_VERSION 268484608
#ifdef NOMINMAX
   #undef NOMINMAX
#endif
#define NOMINMAX
#ifdef __STDC_CONSTANT_MACROS
   #undef __STDC_CONSTANT_MACROS
#endif
#define __STDC_CONSTANT_MACROS 1
#ifdef NIMXL_TRANSLATOR
   #undef NIMXL_TRANSLATOR
#endif
#define NIMXL_TRANSLATOR "mxlator_slscsl"
#ifdef WIN32_LEAN_AND_MEAN
   #undef WIN32_LEAN_AND_MEAN
#endif
#define WIN32_LEAN_AND_MEAN
#ifdef _WIN32
   #undef _WIN32
#endif
#define _WIN32
#ifdef kNIBuildToolsDebug
   #undef kNIBuildToolsDebug
#endif
#define kNIBuildToolsDebug 0
#ifdef NDEBUG
   #undef NDEBUG
#endif
#define NDEBUG
#ifdef kSLSCSLExportSymbols
   #undef kSLSCSLExportSymbols
#endif
#define kSLSCSLExportSymbols
#ifdef NIAPAL_USE_CPP_EXCEPTIONS
   #undef NIAPAL_USE_CPP_EXCEPTIONS
#endif
#define NIAPAL_USE_CPP_EXCEPTIONS 1
#ifdef nNITYPES000_kUseAPALNames
   #undef nNITYPES000_kUseAPALNames
#endif
#define nNITYPES000_kUseAPALNames 1
#ifdef WIN32
   #undef WIN32
#endif
#define WIN32
#ifdef SSNATIVE64
   #undef SSNATIVE64
#endif
#define SSNATIVE64
#ifdef _WIN32_IE
   #undef _WIN32_IE
#endif
#define _WIN32_IE 0x0501
#ifdef kNIBuildToolsProcessor
   #undef kNIBuildToolsProcessor
#endif
#define kNIBuildToolsProcessor "i386"
#ifdef WINVER
   #undef WINVER
#endif
#define WINVER 0x0601
#ifdef kNIBuildToolsTargetName
   #undef kNIBuildToolsTargetName
#endif
#define kNIBuildToolsTargetName "slscsl.dll"
#ifdef kNIBuildToolsRelease
   #undef kNIBuildToolsRelease
#endif
#define kNIBuildToolsRelease 1
#ifdef _CRT_SECURE_NO_WARNINGS
   #undef _CRT_SECURE_NO_WARNINGS
#endif
#define _CRT_SECURE_NO_WARNINGS
#ifdef kNIBuildToolsOSEnv
   #undef kNIBuildToolsOSEnv
#endif
#define kNIBuildToolsOSEnv "win32U"
#ifdef NIMXL_TERMS_HEADER
   #undef NIMXL_TERMS_HEADER
#endif
#define NIMXL_TERMS_HEADER "slscsl/nimxlTerms.h"
#ifdef kSYSTEM_API_NOTIFICATIONS_ENABLED
   #undef kSYSTEM_API_NOTIFICATIONS_ENABLED
#endif
#define kSYSTEM_API_NOTIFICATIONS_ENABLED 0
#ifdef _X86_
   #undef _X86_
#endif
#define _X86_ 1
#endif
